### ISSUE TITLE
关于运行ASGCN中train.py

### ISSUE THREAD

**Issue by Venu-ka** [ROGERDJQ/RoBERTaABSA#10]
dataset, [fn for fn in fns if "Train" in fn and fn.endswith("seg")][0]
IndexError: list index out of range
请问怎么解决

**Comment by ROGERDJQ** [comment]
看起来是目录下并没有包含Train的文件

**Comment by Venu-ka** [comment]
> 看起来是目录下并没有包含Train的文件

感谢提示，知道怎么回事了
