### ISSUE TITLE
请问Sentiment words对于performance的影响大吗

### ISSUE THREAD

**Issue by yangheng95** [ROGERDJQ/RoBERTaABSA#3]

**Comment by ROGERDJQ** [comment]
你好，这里的performance指的是什么performance? 论文中Sentiment words只有在分析环节有提到，用于AsD的计算，并没有直接对应的性能。

**Comment by yangheng95** [comment]
我指的是对acc或者f1有没有提升。我这个问题问的不好，等我看一下代码再跟您讨论
