### ISSUE TITLE
请问您在运行finetune.py时，model_name选择的是“roberta-en”还是“roberta-en-large”？

### ISSUE THREAD

**Issue by fuyao98** [ROGERDJQ/RoBERTaABSA#4]
您好，请问您在运行finetune.py时，model_name选择的是“roberta-en”还是“roberta-en-large”，我用“roberta-en”复现出的结果不太令人满意，但是用“roberta-en-large”是报错的，我无法找出原因，期待您的回答。

**Comment by ROGERDJQ** [comment]
感谢对我们工作的关注。我们使用的是roberta-en的base版本。但是我们在finetune时使用的是fastNLP的embedding模块。另外，如果可以的话，也可以分享下你使用roberta-en的复现结果，我想我们能够解决这个问题，请不要因此沮丧。

**Comment by fuyao98** [comment]
感谢您的回复，我十分欣喜！
根据您的建议，我检查了我的代码，我使用的正是roberta-en的base版本。
对于您说的“在finetune时使用的是fastNLP的embedding模块”，我认为我的操作也是正确的，我是这样做的：按照您的readme下载安装了fastNLP 和 fitlog（pip install fastNLP fitlog）, 也导入了相关的包如“from fastNLP. embeddings import BertWordPieceEncoder, RobertaWordPieceEncoder”（代码中已有）。在运行finetune前我只改动了model_name，dataset和data_dir，其他地方并未改动。请问若要达到您的性能是否还要改动其他地方呢？
另外，我很乐意将我的复现结果分享给您，我只在2个数据集上进行了2个模型的实验，结果如下：
    ASGCN:         
REST14        ACC:    81.70 ,  F1 :  72.29   
 Lap14          ACC:    73.82,   F1 :  69.79
    PWCN:         
 REST14        ACC:    81.25 ,  F1 :  72.48  
 Lap14          ACC:    77.12,   F1 :  72.79

   我比较愚钝，束手无策，望您指点迷津，再次感谢您！

**Comment by ROGERDJQ** [comment]
这里我有一些疑问，如果只是运行finetune.py，该代码中包含的模型只是RoBERTa+MLP, 不包含你所提到的ASGCN, PWCN这两个模型。所以如果只是运行了finetune.py， 应该是无法得到ASGCN和PWCN的结果的。
另外一方面，你这里得到了ASGCN和PWCN，这两个结果更像是使用静态的embedding。 我想可能是跑错了代码。

**Comment by fuyao98** [comment]
感谢您的回复！
对于您指出的第一方面：
我并没有只运行finetune.py，只是我猜测这个文件可能是我复现效果不佳的原因，所以重点说了一下我对finetune.py的操作，是我没有表达清楚，不好意思。我的实际运行顺序是1、finetune.py   2、generate_matrix.py（"--model_path" 为 save_models文件夹下的 roberta）和 generate_matrix.py   3、ASGCN 的 train.py
对于您指出的第二方面：
您说的是正确的。在 ASGCN 的 readme 中 有这样的要求 ：“Download pretrained GloVe embeddings from here and extract glove.840B.300d.txt into glove/.”，于是我使用了glove embedding。所以我只需要将 glove embedding 替换成 bert/robert  embedding ？
期待您的批评与指正，再次感谢您。

**Comment by ROGERDJQ** [comment]
第一部分的顺序是没有问题的。
第二部分，关于bert/roberta版本，从结果角度上确实是将 glove embedding 替换成 bert/robert embedding，但是实现方式上并不是这样实现的。ASGCN/PWCN/RGAT三个模型的加入方式都不太相同。这部分代码可能要具体查看对应模型内的代码。

**Comment by fuyao98** [comment]
非常感谢！！！
