### ISSUE TITLE
[Question]多观点抽出是否支持？

### ISSUE THREAD

**Issue by LangDaoAI** [ROGERDJQ/RoBERTaABSA#5]
想问一下， 这篇paper是否支持<aspect, opinion, sentiment>同时抽出？另外， 中文是否支持？

Best Regards!

**Comment by ROGERDJQ** [comment]
这篇文章主要关注sentiment的分类。关于<aspect, opinion, sentiment>同时抽出的工作，请关注https://arxiv.org/abs/2106.04300

**Comment by LangDaoAI** [comment]
好的，感谢回复！

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
