### ISSUE TITLE
Keyword arguments {'add_special_tokens': True} not recognized.

### ISSUE THREAD

**Issue by RingoTC** [ROGERDJQ/RoBERTaABSA#6]
执行
`python generate_matrix.py --model_path bert --data_dir ../Dataset/ --dataset Tweets`
得到报错
`Keyword arguments {'add_special_tokens': True} not recognized.`
allennlp的版本：2.5.0

**Comment by BD-MF** [comment]
您好 这个问题解决了么？

**Comment by RingoTC** [comment]
去掉这个参数即可。

**Comment by yuhaiyan-77** [comment]
您好去掉哪个参数啊

**Comment by RingoTC** [comment]
> 您好去掉哪个参数啊

add_special_tokens
