### ISSUE TITLE
Evaluate fine-tuned model

### ISSUE THREAD

**Issue by satpalsr** [ROGERDJQ/RoBERTaABSA#8]
Hey, I am trying to obtain SOTA results with RoBARTa.
I have successfully fine-tuned the model using "Train/finetune.py",
but the "infer or evaluate" file is missing for it.
Can you please add how to evaluate the fine-tuned model with examples to obtain the results?

**Comment by ROGERDJQ** [comment]
The process of ''infer or evaluate''  is integrated with the trainer.  https://github.com/ROGERDJQ/RoBERTaABSA/blob/26269111a74b34d0fd70a425ba275c09d7b3fcef/Train/finetune.py#L263 shows the clue for it.

**Comment by satpalsr** [comment]
Thank you. Also, consider adding some input-output examples in README.md along with steps to reproduce.

**Comment by ROGERDJQ** [comment]
Good idea, I will later add them. Thank you.
