### ISSUE TITLE
运行finetune.py提示缺少文件

### ISSUE THREAD

**Issue by z1ouhan** [ROGERDJQ/RoBERTaABSA#9]
OSError: [Errno 22] Invalid argument: 'Train/caches/data_Restaurants_<mask>_roberta-en.pkl'

**Comment by ROGERDJQ** [comment]
'Train/caches/data_Restaurants__roberta-en.pkl'该文件是使用roberta作为表示，并经过预处理后的restaurant的数据集的缓存，并不需要直接作为argument使用
